steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'deploy/Dockerfile.cloudrun'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/muhafiz/muhafizsre:latest'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/muhafiz/muhafizsre:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '900s'
